name = "site-status"
compatibility_date = "2025-06-14"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[vars]
# API URL - required
## Due to potential CORS issues with the official website, you can use a reverse proxy to resolve this (please set it up yourself).
## For more details, please refer to the project README.md.
API_URL="https://api.uptimerobot.com/v2/"

# Deployment platform - required
## cloudflare ( default ) | auto
## If you use a platform other than cloudflare, please change to auto
DEPLOYMENT_PLATFORM="auto"

# Site Title
SITE_TITLE="WearOS 工具箱服务状态"

# Site Description
SITE_DESCRIPTION="WearOS 工具箱相关服务状态实时检测"

# Site Keywords
SITE_KEYWORDS="站点监测,监测,监控"

# Site Logo
SITE_LOGO="/favicon.ico"

# ICP Filing
## In China, you need to provide an ICP (Internet Content Provider) filing number.
## https://beian.miit.gov.cn/
SITE_ICP="浙 ICP 备 2022037395 号-1 "

# Count Days
## The number of days to count
## You are advised to fill in 30 - 90
COUNT_DAYS=60

# Show Links
## Whether to show sites links
SHOW_LINKS=false